### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by marckleinebudde** [ryedwards/BudgetCANv2#1]
Hey,

I think the following files are missing in the repo:
```
STM32G431CB_flash.lds
startup_stm32g431xx.c
```

**Comment by ryedwards** [comment]
Hey Marc,

Sorry it's a bit confusing since I'm using VisualGDB to do all my work at this point.  The startup is actually an assembly file included in the CoreMX:
Drivers\CMSIS\Device\ST\STM32G4xx\Source\Templates\gcc\startup_stm32g431xx.s

I'm not finding any *.lds files in the source tree so not sure if VisualGDB isn't using it.

I wasn't expecting anyone to look at this repository so I guess anything else you find would be appreciated.  It's pretty hacked together right now.  Awaiting someone to start working on an FDCAN version of gs_usb to do any additional work.  Focusing on the MCP2518FD for my current project (which you are also working on).

**Comment by marckleinebudde** [comment]
Hey @ryedwards,

I was trying to compile the source with `make` and it fails with:
```
make: *** No rule to make target '/STM32G4xxxx/StartupFiles/startup_stm32g431xx.c', needed by 'Debug/startup_stm32g431xx.o'.  Stop.
```

...as `startup_stm32g431xx.c` is listed in

https://github.com/ryedwards/BudgetCANv2/blob/f122ee61bf3cabf9c0b139c510304495e82509cb/Makefile#L67

I probably have to define `BSP_ROOT` for all this to work. Is `BSP_ROOT` an external component I have to download and install separately?

**Comment by ryedwards** [comment]
Yes.  BSP_ROOT is part of VisualGDB.  I've uploaded those two files from the BSP into the root directory.  See if you can edit the Makefile to pull them in and see if it works.

**Comment by marckleinebudde** [comment]
With moving the files around I can build the firmware now. See https://github.com/ryedwards/BudgetCANv2/pull/2
